--------------------------------------------------------
-- Archivo creado  - miércoles-febrero-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DBOBJECTID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."DBOBJECTID_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 50 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_CARRERA
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_CARRERA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_CURSO
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_CURSO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_GENERO
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_GENERO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_MATERIA
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_MATERIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_MATRICULA
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_MATRICULA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_ROL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_TAREA
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_TAREA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_TAREA_ENTREGADA
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_TAREA_ENTREGADA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "C##PIS_U"."INCREMENTO_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TB_CARRERA
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_CARRERA" 
   (	"ID" NUMBER, 
	"CR_FACULTAD" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ID_ASIGNADO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  NO INMEMORY ("ID") ;

   COMMENT ON COLUMN "C##PIS_U"."TB_CARRERA"."ID" IS 'identificador de la carrera';
   COMMENT ON COLUMN "C##PIS_U"."TB_CARRERA"."CR_FACULTAD" IS 'facultad de la carrera';
   COMMENT ON COLUMN "C##PIS_U"."TB_CARRERA"."DESCRIPCION" IS 'descripcion de la carrera';
   COMMENT ON COLUMN "C##PIS_U"."TB_CARRERA"."ID_ASIGNADO" IS 'sirve para saber el docente asignado a la carrera';
   COMMENT ON COLUMN "C##PIS_U"."TB_CARRERA"."NOMBRE" IS 'nombre de la carrera';
   COMMENT ON COLUMN "C##PIS_U"."TB_CARRERA"."ESTADO" IS 'estado de la carrera, activo o pasivo';
--------------------------------------------------------
--  DDL for Table TB_CURSO
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_CURSO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ID_CARRERA" NUMBER, 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PIS_U"."TB_CURSO"."ID" IS 'identificador del curso';
   COMMENT ON COLUMN "C##PIS_U"."TB_CURSO"."NOMBRE" IS 'nombre del curso';
   COMMENT ON COLUMN "C##PIS_U"."TB_CURSO"."DESCRIPCION" IS 'descripcion del curso';
   COMMENT ON COLUMN "C##PIS_U"."TB_CURSO"."ID_CARRERA" IS 'sirve para saber de que carrera es el curso';
   COMMENT ON COLUMN "C##PIS_U"."TB_CURSO"."ESTADO" IS 'estado del curso, activo o pasivo';
--------------------------------------------------------
--  DDL for Table TB_GENERO
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_GENERO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PIS_U"."TB_GENERO"."ID" IS 'identificacion del genero';
   COMMENT ON COLUMN "C##PIS_U"."TB_GENERO"."NOMBRE" IS 'nombre con el que se conoce al genero';
   COMMENT ON COLUMN "C##PIS_U"."TB_GENERO"."DESCRIPCION" IS 'descripcion del genero';
   COMMENT ON COLUMN "C##PIS_U"."TB_GENERO"."ESTADO" IS 'estado del genero, activo o pasivo';
--------------------------------------------------------
--  DDL for Table TB_MATERIA
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_MATERIA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"MA_NOTA" NUMBER(6,2), 
	"ESTADO" CHAR(1 BYTE), 
	"ID_CURSO" NUMBER, 
	"ID_DOCENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."ID" IS 'identificador de la materia';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."NOMBRE" IS 'nombre de la materia';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."DESCRIPCION" IS 'descripcion de la materia';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."MA_NOTA" IS 'nota de la materia';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."ESTADO" IS 'estado de la materia, activo o pasivo';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."ID_CURSO" IS 'sirve para saber de que curso es la materia';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATERIA"."ID_DOCENTE" IS 'sirve para saber a que docente imparte la materia';
--------------------------------------------------------
--  DDL for Table TB_MATRICULA
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_MATRICULA" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ESTADO" CHAR(1 BYTE), 
	"MT_NUMERO_MATRICULA" VARCHAR2(100 BYTE), 
	"MT_ESTADO_ESTUDIANTE" VARCHAR2(20 BYTE), 
	"MT_NOTA_FINAL" NUMBER(6,2), 
	"ID_ESTUDIANTE" NUMBER, 
	"ID_CURSO" NUMBER, 
	"MT_FECHA_INICIO" DATE, 
	"MT_FECHA_CULMINACION" DATE, 
	"MT_ESTADO_MATRICULA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."ID" IS 'identificador de la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."NOMBRE" IS 'nombre de la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."DESCRIPCION" IS 'descripcion de la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."ESTADO" IS 'estado de la matricula, activo o pasivo';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."MT_NUMERO_MATRICULA" IS 'nos dice el numero de la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."MT_ESTADO_ESTUDIANTE" IS 'nos dice el estado de la matricula del estudiante, aprobado o reprobado';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."MT_NOTA_FINAL" IS 'nota final de la matricula del estudiante';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."ID_ESTUDIANTE" IS 'sirve para saber de que estudiante es la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."ID_CURSO" IS 'sirve para saber de que curso es la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."MT_FECHA_INICIO" IS 'fecha de inicio de la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."MT_FECHA_CULMINACION" IS 'fecha de culminacion de la matricula';
   COMMENT ON COLUMN "C##PIS_U"."TB_MATRICULA"."MT_ESTADO_MATRICULA" IS 'define el estado de la matricula, cursando o no';
--------------------------------------------------------
--  DDL for Table TB_ROL
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_ROL" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  NO INMEMORY ("ID") ;

   COMMENT ON COLUMN "C##PIS_U"."TB_ROL"."ID" IS 'identificador del rol';
   COMMENT ON COLUMN "C##PIS_U"."TB_ROL"."NOMBRE" IS 'nombre del rol';
   COMMENT ON COLUMN "C##PIS_U"."TB_ROL"."DESCRIPCION" IS 'descripcion del rol';
   COMMENT ON COLUMN "C##PIS_U"."TB_ROL"."ESTADO" IS 'estado del rol, activo o pasivo';
--------------------------------------------------------
--  DDL for Table TB_TAREA
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_TAREA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"TA_FECHA_CREACION" DATE, 
	"TA_FECHA_ENTREGA" DATE, 
	"DESCRIPCION" NVARCHAR2(2000), 
	"ESTADO" CHAR(1 BYTE), 
	"ID_MATERIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  NO INMEMORY ("DESCRIPCION") 
  NO INMEMORY ("ID") ;

   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."ID" IS 'identificador de la tarea';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."NOMBRE" IS 'nombre de la tarea';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."TA_FECHA_CREACION" IS 'fecha de creacion de la tarea';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."TA_FECHA_ENTREGA" IS 'fecha de entrega de la tarea';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."DESCRIPCION" IS 'descripcion de la tarea';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."ESTADO" IS 'estado de la tarea, activo o pasivo';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA"."ID_MATERIA" IS 'sirve para saber de que materia es la tarea';
--------------------------------------------------------
--  DDL for Table TB_TAREA_ENTREGADA
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" 
   (	"ID" NUMBER, 
	"DESCRIPCION" NVARCHAR2(2000), 
	"ESTADO" CHAR(1 BYTE), 
	"TE_NOTA" NUMBER(6,2), 
	"ID_ESTUDIANTE" NUMBER, 
	"ID_TAREA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA_ENTREGADA"."ID" IS 'identificador de la tarea entregada';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA_ENTREGADA"."DESCRIPCION" IS 'descripcion de la tarea entregada';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA_ENTREGADA"."ESTADO" IS 'estado de la tarea entregada, activo o pasivo';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA_ENTREGADA"."TE_NOTA" IS 'nota de la tarea entregada';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA_ENTREGADA"."ID_ESTUDIANTE" IS 'sirve para ver a que estudiante pertenece la tarea entregada';
   COMMENT ON COLUMN "C##PIS_U"."TB_TAREA_ENTREGADA"."ID_TAREA" IS 'sirve para identificar a que tarea pertence la tarea entregada';
--------------------------------------------------------
--  DDL for Table TB_USUARIO
--------------------------------------------------------

  CREATE TABLE "C##PIS_U"."TB_USUARIO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"ESTADO" CHAR(1 BYTE), 
	"USU_CORREO_ELECTRONICO" VARCHAR2(100 BYTE), 
	"USU_CONTRASENIA" VARCHAR2(100 BYTE), 
	"ID_ROL" NUMBER, 
	"ID_GENERO" NUMBER, 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"CEDULA" VARCHAR2(10 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."ID" IS 'identificador del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."NOMBRE" IS 'nombre del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."APELLIDO" IS 'apellido del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."ESTADO" IS 'estado del usuario, activo o pasivo';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."USU_CORREO_ELECTRONICO" IS 'correo electronico del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."USU_CONTRASENIA" IS 'contrasenia del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."ID_ROL" IS 'sirve para saber el rol del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."ID_GENERO" IS 'sirve para saber el genero del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."DESCRIPCION" IS 'descripcion del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."CEDULA" IS 'cedula del usuario';
   COMMENT ON COLUMN "C##PIS_U"."TB_USUARIO"."TELEFONO" IS 'numero del telefono celular del usuario';
--------------------------------------------------------
--  DDL for View CARRERA_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."CARRERA_VIEW" ("CARRERA_ID", "FACULTAD", "DESCRIPCION", "DOCENTE_ASIGNADO_ID", "NOMBRE", "ESTADO") AS 
  SELECT
    ID AS carrera_id,
    CR_FACULTAD AS facultad,
    DESCRIPCION AS descripcion,
    ID_ASIGNADO AS docente_asignado_id,
    NOMBRE AS nombre,
    ESTADO AS estado
FROM
    "C##PIS_U"."TB_CARRERA"
;
--------------------------------------------------------
--  DDL for View CURSO_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."CURSO_VIEW" ("CURSO_ID", "CURSO_NOMBRE", "CURSO_DESCRIPCION", "CARRERA_ID", "CARRERA_NOMBRE", "CURSO_ESTADO") AS 
  SELECT
    c.ID AS curso_id,
    c.NOMBRE AS curso_nombre,
    c.DESCRIPCION AS curso_descripcion,
    c.ID_CARRERA AS carrera_id,
    ca.NOMBRE AS carrera_nombre,
    c.ESTADO AS curso_estado
FROM
    "C##PIS_U"."TB_CURSO" c
JOIN
    "C##PIS_U"."TB_CARRERA" ca ON c.ID_CARRERA = ca.ID
;
--------------------------------------------------------
--  DDL for View GENERO_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."GENERO_VIEW" ("GENERO_ID", "GENERO_NOMBRE", "GENERO_DESCRIPCION", "GENERO_ESTADO") AS 
  SELECT
    ID AS genero_id,
    NOMBRE AS genero_nombre,
    DESCRIPCION AS genero_descripcion,
    ESTADO AS genero_estado
FROM
    "C##PIS_U"."TB_GENERO"
;
--------------------------------------------------------
--  DDL for View MATERIA_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."MATERIA_VIEW" ("MATERIA_ID", "MATERIA_NOMBRE", "MATERIA_DESCRIPCION", "MATERIA_NOTA", "MATERIA_ESTADO", "CURSO_ID", "DOCENTE_ID") AS 
  SELECT
    ID AS materia_id,
    NOMBRE AS materia_nombre,
    DESCRIPCION AS materia_descripcion,
    MA_NOTA AS materia_nota,
    ESTADO AS materia_estado,
    ID_CURSO AS curso_id,
    ID_DOCENTE AS docente_id
FROM
    "C##PIS_U"."TB_MATERIA"
;
--------------------------------------------------------
--  DDL for View MATRICULA_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."MATRICULA_VIEW" ("MATRICULA_ID", "MATRICULA_NOMBRE", "MATRICULA_DESCRIPCION", "MATRICULA_ESTADO", "NUMERO_MATRICULA", "ESTADO_ESTUDIANTE", "NOTA_FINAL", "ESTUDIANTE_ID", "CURSO_ID", "FECHA_INICIO", "FECHA_CULMINACION", "ESTADO_MATRICULA") AS 
  SELECT
    ID AS matricula_id,
    NOMBRE AS matricula_nombre,
    DESCRIPCION AS matricula_descripcion,
    ESTADO AS matricula_estado,
    MT_NUMERO_MATRICULA AS numero_matricula,
    MT_ESTADO_ESTUDIANTE AS estado_estudiante,
    MT_NOTA_FINAL AS nota_final,
    ID_ESTUDIANTE AS estudiante_id,
    ID_CURSO AS curso_id,
    MT_FECHA_INICIO AS fecha_inicio,
    MT_FECHA_CULMINACION AS fecha_culminacion,
    MT_ESTADO_MATRICULA AS estado_matricula
FROM
    "C##PIS_U"."TB_MATRICULA"
;
--------------------------------------------------------
--  DDL for View ROL_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."ROL_VIEW" ("ROL_ID", "ROL_NOMBRE", "ROL_DESCRIPCION", "ROL_ESTADO") AS 
  SELECT
    ID AS rol_id,
    NOMBRE AS rol_nombre,
    DESCRIPCION AS rol_descripcion,
    ESTADO AS rol_estado
FROM
    "C##PIS_U"."TB_ROL"
;
--------------------------------------------------------
--  DDL for View TAREA_ENTREGADA_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."TAREA_ENTREGADA_VIEW" ("TAREA_ENTREGADA_ID", "TAREA_ENTREGADA_DESCRIPCION", "TAREA_ENTREGADA_ESTADO", "TAREA_ENTREGADA_NOTA", "ESTUDIANTE_ID", "TAREA_ID") AS 
  SELECT
    ID AS tarea_entregada_id,
    DESCRIPCION AS tarea_entregada_descripcion,
    ESTADO AS tarea_entregada_estado,
    TE_NOTA AS tarea_entregada_nota,
    ID_ESTUDIANTE AS estudiante_id,
    ID_TAREA AS tarea_id
FROM
    "C##PIS_U"."TB_TAREA_ENTREGADA"
;
--------------------------------------------------------
--  DDL for View TAREA_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."TAREA_VIEW" ("TAREA_ID", "TAREA_NOMBRE", "TAREA_FECHA_CREACION", "TAREA_FECHA_ENTREGA", "TAREA_DESCRIPCION", "TAREA_ESTADO", "MATERIA_ID") AS 
  SELECT
    ID AS tarea_id,
    NOMBRE AS tarea_nombre,
    TA_FECHA_CREACION AS tarea_fecha_creacion,
    TA_FECHA_ENTREGA AS tarea_fecha_entrega,
    DESCRIPCION AS tarea_descripcion,
    ESTADO AS tarea_estado,
    ID_MATERIA AS materia_id
FROM
    "C##PIS_U"."TB_TAREA"
;
--------------------------------------------------------
--  DDL for View USUARIO_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##PIS_U"."USUARIO_VIEW" ("USUARIO_ID", "NOMBRE", "APELLIDO", "ESTADO", "CORREO_ELECTRONICO", "CONTRASENIA", "ROL_ID", "GENERO_ID", "DESCRIPCION", "CEDULA", "TELEFONO") AS 
  SELECT
    ID AS usuario_id,
    NOMBRE AS nombre,
    APELLIDO AS apellido,
    ESTADO AS estado,
    USU_CORREO_ELECTRONICO AS correo_electronico,
    USU_CONTRASENIA AS contrasenia,
    ID_ROL AS rol_id,
    ID_GENERO AS genero_id,
    DESCRIPCION AS descripcion,
    CEDULA AS cedula,
    TELEFONO AS telefono
FROM
    "C##PIS_U"."TB_USUARIO"
;
REM INSERTING into C##PIS_U.TB_CARRERA
SET DEFINE OFF;
Insert into C##PIS_U.TB_CARRERA (ID,CR_FACULTAD,DESCRIPCION,ID_ASIGNADO,NOMBRE,ESTADO) values ('4','FEIRNNR','qwerty','24','Minas','A');
Insert into C##PIS_U.TB_CARRERA (ID,CR_FACULTAD,DESCRIPCION,ID_ASIGNADO,NOMBRE,ESTADO) values ('5','FEIRNNR',null,'22','Computacion','A');
Insert into C##PIS_U.TB_CARRERA (ID,CR_FACULTAD,DESCRIPCION,ID_ASIGNADO,NOMBRE,ESTADO) values ('6','Salud',null,'22','Psicologia','A');
REM INSERTING into C##PIS_U.TB_CURSO
SET DEFINE OFF;
Insert into C##PIS_U.TB_CURSO (ID,NOMBRE,DESCRIPCION,ID_CARRERA,ESTADO) values ('3','Tercer Ciclo A','asdfghjk','4','A');
Insert into C##PIS_U.TB_CURSO (ID,NOMBRE,DESCRIPCION,ID_CARRERA,ESTADO) values ('4','Primer Ciclo A',null,'5','A');
REM INSERTING into C##PIS_U.TB_GENERO
SET DEFINE OFF;
Insert into C##PIS_U.TB_GENERO (ID,NOMBRE,DESCRIPCION,ESTADO) values ('1','HOMBRE',null,'A');
Insert into C##PIS_U.TB_GENERO (ID,NOMBRE,DESCRIPCION,ESTADO) values ('2','MUJER',null,'A');
Insert into C##PIS_U.TB_GENERO (ID,NOMBRE,DESCRIPCION,ESTADO) values ('3','OTRO',null,'A');
REM INSERTING into C##PIS_U.TB_MATERIA
SET DEFINE OFF;
Insert into C##PIS_U.TB_MATERIA (ID,NOMBRE,DESCRIPCION,MA_NOTA,ESTADO,ID_CURSO,ID_DOCENTE) values ('3','Algebra',null,'7','A','3','24');
REM INSERTING into C##PIS_U.TB_MATRICULA
SET DEFINE OFF;
Insert into C##PIS_U.TB_MATRICULA (ID,NOMBRE,DESCRIPCION,ESTADO,MT_NUMERO_MATRICULA,MT_ESTADO_ESTUDIANTE,MT_NOTA_FINAL,ID_ESTUDIANTE,ID_CURSO,MT_FECHA_INICIO,MT_FECHA_CULMINACION,MT_ESTADO_MATRICULA) values ('3','Matricula OCT24-MAR24',null,'A','1','CURSANDO','0','23','3',to_date('20/02/2024','DD/MM/RRRR'),to_date('29/02/2024','DD/MM/RRRR'),'MATRICULADO');
Insert into C##PIS_U.TB_MATRICULA (ID,NOMBRE,DESCRIPCION,ESTADO,MT_NUMERO_MATRICULA,MT_ESTADO_ESTUDIANTE,MT_NOTA_FINAL,ID_ESTUDIANTE,ID_CURSO,MT_FECHA_INICIO,MT_FECHA_CULMINACION,MT_ESTADO_MATRICULA) values ('4','Matricula ABR24-JUL24',null,'P','1','CURSANDO','0','23','4',to_date('20/02/2024','DD/MM/RRRR'),to_date('29/02/2024','DD/MM/RRRR'),'RETIRADO');
Insert into C##PIS_U.TB_MATRICULA (ID,NOMBRE,DESCRIPCION,ESTADO,MT_NUMERO_MATRICULA,MT_ESTADO_ESTUDIANTE,MT_NOTA_FINAL,ID_ESTUDIANTE,ID_CURSO,MT_FECHA_INICIO,MT_FECHA_CULMINACION,MT_ESTADO_MATRICULA) values ('5','Matricula SEA 2023',null,'A','2','CURSANDO','0','23','4',to_date('20/02/2024','DD/MM/RRRR'),to_date('20/02/2024','DD/MM/RRRR'),'MATRICULADO');
Insert into C##PIS_U.TB_MATRICULA (ID,NOMBRE,DESCRIPCION,ESTADO,MT_NUMERO_MATRICULA,MT_ESTADO_ESTUDIANTE,MT_NOTA_FINAL,ID_ESTUDIANTE,ID_CURSO,MT_FECHA_INICIO,MT_FECHA_CULMINACION,MT_ESTADO_MATRICULA) values ('6','Matricula ABR-OCT',null,'P','1','CURSANDO','0','25','3',to_date('21/02/2024','DD/MM/RRRR'),to_date('21/02/2024','DD/MM/RRRR'),'RETIRADO');
Insert into C##PIS_U.TB_MATRICULA (ID,NOMBRE,DESCRIPCION,ESTADO,MT_NUMERO_MATRICULA,MT_ESTADO_ESTUDIANTE,MT_NOTA_FINAL,ID_ESTUDIANTE,ID_CURSO,MT_FECHA_INICIO,MT_FECHA_CULMINACION,MT_ESTADO_MATRICULA) values ('8','Matricula JUN',null,'A','1','CURSANDO','0','25','4',to_date('21/02/2024','DD/MM/RRRR'),to_date('21/02/2024','DD/MM/RRRR'),'MATRICULADO');
REM INSERTING into C##PIS_U.TB_ROL
SET DEFINE OFF;
Insert into C##PIS_U.TB_ROL (ID,NOMBRE,DESCRIPCION,ESTADO) values ('1','ADMINISTRADOR',null,'A');
Insert into C##PIS_U.TB_ROL (ID,NOMBRE,DESCRIPCION,ESTADO) values ('2','DOCENTE',null,'A');
Insert into C##PIS_U.TB_ROL (ID,NOMBRE,DESCRIPCION,ESTADO) values ('3','ESTUDIANTE',null,'A');
REM INSERTING into C##PIS_U.TB_TAREA
SET DEFINE OFF;
Insert into C##PIS_U.TB_TAREA (ID,NOMBRE,TA_FECHA_CREACION,TA_FECHA_ENTREGA,DESCRIPCION,ESTADO,ID_MATERIA) values ('4','Practica minas',to_date('20/02/2024','DD/MM/RRRR'),to_date('21/02/2024','DD/MM/RRRR'),'asdasfsdas

www.eva.edu.ec','A','3');
Insert into C##PIS_U.TB_TAREA (ID,NOMBRE,TA_FECHA_CREACION,TA_FECHA_ENTREGA,DESCRIPCION,ESTADO,ID_MATERIA) values ('5','Investigacion',to_date('21/02/2024','DD/MM/RRRR'),to_date('25/02/2024','DD/MM/RRRR'),'qwertyuiopasdfghjk','A','3');
REM INSERTING into C##PIS_U.TB_TAREA_ENTREGADA
SET DEFINE OFF;
Insert into C##PIS_U.TB_TAREA_ENTREGADA (ID,DESCRIPCION,ESTADO,TE_NOTA,ID_ESTUDIANTE,ID_TAREA) values ('3','sxsx','A','0','23','4');
Insert into C##PIS_U.TB_TAREA_ENTREGADA (ID,DESCRIPCION,ESTADO,TE_NOTA,ID_ESTUDIANTE,ID_TAREA) values ('4','asdfghjklpoiuytrewzc,','A','8','23','5');
REM INSERTING into C##PIS_U.TB_USUARIO
SET DEFINE OFF;
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('21','Wilman Alejandro','Morocho Carrion','P','wilman.morocho@gmail.com','utXzrtJzPhWBDItbBQkwVw==','3','1','estudiante tercer ciclo','1106002593','0969262775');
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('24','Mariuxi Alexandra','Valdez Cuenca','A','mariuxi.valdez@gmail.com','JljMPkUhGmY=','2','2','docente sea','1106039439','0987121231');
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('23','Luis Miguel','Hidalgo Santos','A','luis.hidalgo@gmail.com','tgw/Cv9AkTI=','3','1','estudiante de tercer ciclo','1105630709','0980678647');
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('1','Usuario','Administrador','A','admin','CWlaarcP6EE=','1','1',null,'1104955107','0986023910');
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('22','Andersson Leandro','Ambuludi Gomez','A','andersson.ambuludi@gmail.com','eGEyNuGltLJjskSjo2u4mQ==','2','1','docente de tercer ciclo','1150592754','0980081647');
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('25','Cristian David','Ajila Asanza','A','cristian@gmail.com','CWlaarcP6EE=','3','1',null,'1150182051','0987654333');
Insert into C##PIS_U.TB_USUARIO (ID,NOMBRE,APELLIDO,ESTADO,USU_CORREO_ELECTRONICO,USU_CONTRASENIA,ID_ROL,ID_GENERO,DESCRIPCION,CEDULA,TELEFONO) values ('26','Juan Fernando','Perez Duaz','A','juan@gmail.com','CWlaarcP6EE=','3','1',null,'1106002593','0987654322');
REM INSERTING into C##PIS_U.CARRERA_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.CARRERA_VIEW (CARRERA_ID,FACULTAD,DESCRIPCION,DOCENTE_ASIGNADO_ID,NOMBRE,ESTADO) values ('4','FEIRNNR','qwerty','24','Minas','A');
Insert into C##PIS_U.CARRERA_VIEW (CARRERA_ID,FACULTAD,DESCRIPCION,DOCENTE_ASIGNADO_ID,NOMBRE,ESTADO) values ('5','FEIRNNR',null,'22','Computacion','A');
Insert into C##PIS_U.CARRERA_VIEW (CARRERA_ID,FACULTAD,DESCRIPCION,DOCENTE_ASIGNADO_ID,NOMBRE,ESTADO) values ('6','Salud',null,'22','Psicologia','A');
REM INSERTING into C##PIS_U.CURSO_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.CURSO_VIEW (CURSO_ID,CURSO_NOMBRE,CURSO_DESCRIPCION,CARRERA_ID,CARRERA_NOMBRE,CURSO_ESTADO) values ('3','Tercer Ciclo A','asdfghjk','4','Minas','A');
Insert into C##PIS_U.CURSO_VIEW (CURSO_ID,CURSO_NOMBRE,CURSO_DESCRIPCION,CARRERA_ID,CARRERA_NOMBRE,CURSO_ESTADO) values ('4','Primer Ciclo A',null,'5','Computacion','A');
REM INSERTING into C##PIS_U.GENERO_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.GENERO_VIEW (GENERO_ID,GENERO_NOMBRE,GENERO_DESCRIPCION,GENERO_ESTADO) values ('1','HOMBRE',null,'A');
Insert into C##PIS_U.GENERO_VIEW (GENERO_ID,GENERO_NOMBRE,GENERO_DESCRIPCION,GENERO_ESTADO) values ('2','MUJER',null,'A');
Insert into C##PIS_U.GENERO_VIEW (GENERO_ID,GENERO_NOMBRE,GENERO_DESCRIPCION,GENERO_ESTADO) values ('3','OTRO',null,'A');
REM INSERTING into C##PIS_U.MATERIA_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.MATERIA_VIEW (MATERIA_ID,MATERIA_NOMBRE,MATERIA_DESCRIPCION,MATERIA_NOTA,MATERIA_ESTADO,CURSO_ID,DOCENTE_ID) values ('3','Algebra',null,'7','A','3','24');
REM INSERTING into C##PIS_U.MATRICULA_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.MATRICULA_VIEW (MATRICULA_ID,MATRICULA_NOMBRE,MATRICULA_DESCRIPCION,MATRICULA_ESTADO,NUMERO_MATRICULA,ESTADO_ESTUDIANTE,NOTA_FINAL,ESTUDIANTE_ID,CURSO_ID,FECHA_INICIO,FECHA_CULMINACION,ESTADO_MATRICULA) values ('3','Matricula OCT24-MAR24',null,'A','1','CURSANDO','0','23','3',to_date('20/02/2024','DD/MM/RRRR'),to_date('29/02/2024','DD/MM/RRRR'),'MATRICULADO');
Insert into C##PIS_U.MATRICULA_VIEW (MATRICULA_ID,MATRICULA_NOMBRE,MATRICULA_DESCRIPCION,MATRICULA_ESTADO,NUMERO_MATRICULA,ESTADO_ESTUDIANTE,NOTA_FINAL,ESTUDIANTE_ID,CURSO_ID,FECHA_INICIO,FECHA_CULMINACION,ESTADO_MATRICULA) values ('4','Matricula ABR24-JUL24',null,'P','1','CURSANDO','0','23','4',to_date('20/02/2024','DD/MM/RRRR'),to_date('29/02/2024','DD/MM/RRRR'),'RETIRADO');
Insert into C##PIS_U.MATRICULA_VIEW (MATRICULA_ID,MATRICULA_NOMBRE,MATRICULA_DESCRIPCION,MATRICULA_ESTADO,NUMERO_MATRICULA,ESTADO_ESTUDIANTE,NOTA_FINAL,ESTUDIANTE_ID,CURSO_ID,FECHA_INICIO,FECHA_CULMINACION,ESTADO_MATRICULA) values ('5','Matricula SEA 2023',null,'A','2','CURSANDO','0','23','4',to_date('20/02/2024','DD/MM/RRRR'),to_date('20/02/2024','DD/MM/RRRR'),'MATRICULADO');
Insert into C##PIS_U.MATRICULA_VIEW (MATRICULA_ID,MATRICULA_NOMBRE,MATRICULA_DESCRIPCION,MATRICULA_ESTADO,NUMERO_MATRICULA,ESTADO_ESTUDIANTE,NOTA_FINAL,ESTUDIANTE_ID,CURSO_ID,FECHA_INICIO,FECHA_CULMINACION,ESTADO_MATRICULA) values ('6','Matricula ABR-OCT',null,'P','1','CURSANDO','0','25','3',to_date('21/02/2024','DD/MM/RRRR'),to_date('21/02/2024','DD/MM/RRRR'),'RETIRADO');
Insert into C##PIS_U.MATRICULA_VIEW (MATRICULA_ID,MATRICULA_NOMBRE,MATRICULA_DESCRIPCION,MATRICULA_ESTADO,NUMERO_MATRICULA,ESTADO_ESTUDIANTE,NOTA_FINAL,ESTUDIANTE_ID,CURSO_ID,FECHA_INICIO,FECHA_CULMINACION,ESTADO_MATRICULA) values ('8','Matricula JUN',null,'A','1','CURSANDO','0','25','4',to_date('21/02/2024','DD/MM/RRRR'),to_date('21/02/2024','DD/MM/RRRR'),'MATRICULADO');
REM INSERTING into C##PIS_U.ROL_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.ROL_VIEW (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,ROL_ESTADO) values ('1','ADMINISTRADOR',null,'A');
Insert into C##PIS_U.ROL_VIEW (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,ROL_ESTADO) values ('2','DOCENTE',null,'A');
Insert into C##PIS_U.ROL_VIEW (ROL_ID,ROL_NOMBRE,ROL_DESCRIPCION,ROL_ESTADO) values ('3','ESTUDIANTE',null,'A');
REM INSERTING into C##PIS_U.TAREA_ENTREGADA_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.TAREA_ENTREGADA_VIEW (TAREA_ENTREGADA_ID,TAREA_ENTREGADA_DESCRIPCION,TAREA_ENTREGADA_ESTADO,TAREA_ENTREGADA_NOTA,ESTUDIANTE_ID,TAREA_ID) values ('3','sxsx','A','0','23','4');
Insert into C##PIS_U.TAREA_ENTREGADA_VIEW (TAREA_ENTREGADA_ID,TAREA_ENTREGADA_DESCRIPCION,TAREA_ENTREGADA_ESTADO,TAREA_ENTREGADA_NOTA,ESTUDIANTE_ID,TAREA_ID) values ('4','asdfghjklpoiuytrewzc,','A','8','23','5');
REM INSERTING into C##PIS_U.TAREA_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.TAREA_VIEW (TAREA_ID,TAREA_NOMBRE,TAREA_FECHA_CREACION,TAREA_FECHA_ENTREGA,TAREA_DESCRIPCION,TAREA_ESTADO,MATERIA_ID) values ('4','Practica minas',to_date('20/02/2024','DD/MM/RRRR'),to_date('21/02/2024','DD/MM/RRRR'),'asdasfsdas

www.eva.edu.ec','A','3');
Insert into C##PIS_U.TAREA_VIEW (TAREA_ID,TAREA_NOMBRE,TAREA_FECHA_CREACION,TAREA_FECHA_ENTREGA,TAREA_DESCRIPCION,TAREA_ESTADO,MATERIA_ID) values ('5','Investigacion',to_date('21/02/2024','DD/MM/RRRR'),to_date('25/02/2024','DD/MM/RRRR'),'qwertyuiopasdfghjk','A','3');
REM INSERTING into C##PIS_U.USUARIO_VIEW
SET DEFINE OFF;
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('21','Wilman Alejandro','Morocho Carrion','P','wilman.morocho@gmail.com','utXzrtJzPhWBDItbBQkwVw==','3','1','estudiante tercer ciclo','1106002593','0969262775');
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('24','Mariuxi Alexandra','Valdez Cuenca','A','mariuxi.valdez@gmail.com','JljMPkUhGmY=','2','2','docente sea','1106039439','0987121231');
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('23','Luis Miguel','Hidalgo Santos','A','luis.hidalgo@gmail.com','tgw/Cv9AkTI=','3','1','estudiante de tercer ciclo','1105630709','0980678647');
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('1','Usuario','Administrador','A','admin','CWlaarcP6EE=','1','1',null,'1104955107','0986023910');
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('22','Andersson Leandro','Ambuludi Gomez','A','andersson.ambuludi@gmail.com','eGEyNuGltLJjskSjo2u4mQ==','2','1','docente de tercer ciclo','1150592754','0980081647');
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('25','Cristian David','Ajila Asanza','A','cristian@gmail.com','CWlaarcP6EE=','3','1',null,'1150182051','0987654333');
Insert into C##PIS_U.USUARIO_VIEW (USUARIO_ID,NOMBRE,APELLIDO,ESTADO,CORREO_ELECTRONICO,CONTRASENIA,ROL_ID,GENERO_ID,DESCRIPCION,CEDULA,TELEFONO) values ('26','Juan Fernando','Perez Duaz','A','juan@gmail.com','CWlaarcP6EE=','3','1',null,'1106002593','0987654322');
--------------------------------------------------------
--  DDL for Index TB_CARRERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_CARRERA_PK" ON "C##PIS_U"."TB_CARRERA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CURSO_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_CURSO_PK1" ON "C##PIS_U"."TB_CURSO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_GENERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_GENERO_PK" ON "C##PIS_U"."TB_GENERO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_MATERIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_MATERIA_PK" ON "C##PIS_U"."TB_MATERIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_MATRICULA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_MATRICULA_PK" ON "C##PIS_U"."TB_MATRICULA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_ROL_PK" ON "C##PIS_U"."TB_ROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_TAREA_ENTREGADA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_TAREA_ENTREGADA_PK" ON "C##PIS_U"."TB_TAREA_ENTREGADA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_TAREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_TAREA_PK" ON "C##PIS_U"."TB_TAREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_USUARIO_PK" ON "C##PIS_U"."TB_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CARRERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_CARRERA_PK" ON "C##PIS_U"."TB_CARRERA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CURSO_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_CURSO_PK1" ON "C##PIS_U"."TB_CURSO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_GENERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_GENERO_PK" ON "C##PIS_U"."TB_GENERO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_MATERIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_MATERIA_PK" ON "C##PIS_U"."TB_MATERIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_MATRICULA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_MATRICULA_PK" ON "C##PIS_U"."TB_MATRICULA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_ROL_PK" ON "C##PIS_U"."TB_ROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_TAREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_TAREA_PK" ON "C##PIS_U"."TB_TAREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_TAREA_ENTREGADA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_TAREA_ENTREGADA_PK" ON "C##PIS_U"."TB_TAREA_ENTREGADA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PIS_U"."TB_USUARIO_PK" ON "C##PIS_U"."TB_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_CARRERA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_CARRERA" 
BEFORE INSERT ON TB_CARRERA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_CARRERA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_CARRERA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CURSO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_CURSO" 
BEFORE INSERT ON TB_CURSO
FOR EACH ROW
BEGIN
SELECT INCREMENTO_CURSO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_CURSO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_GENERO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_GENERO" 
BEFORE INSERT ON TB_GENERO
FOR EACH ROW
BEGIN
SELECT INCREMENTO_GENERO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_GENERO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_MATERIA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_MATERIA" 
BEFORE INSERT ON TB_MATERIA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_MATERIA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_MATERIA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_MATRICULA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_MATRICULA" 
BEFORE INSERT ON TB_MATRICULA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_MATRICULA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_MATRICULA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_ROL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_ROL" 
BEFORE INSERT ON TB_ROL
FOR EACH ROW
BEGIN
SELECT INCREMENTO_ROL.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_ROL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_TAREA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_TAREA" 
BEFORE INSERT ON TB_TAREA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_TAREA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_TAREA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_TAREA_ENTREGADA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_TAREA_ENTREGADA" 
BEFORE INSERT ON TB_TAREA_ENTREGADA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_TAREA_ENTREGADA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_TAREA_ENTREGADA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_USUARIO" 
BEFORE INSERT ON TB_USUARIO
FOR EACH ROW
BEGIN
SELECT INCREMENTO_USUARIO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CARRERA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_CARRERA" 
BEFORE INSERT ON TB_CARRERA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_CARRERA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_CARRERA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CURSO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_CURSO" 
BEFORE INSERT ON TB_CURSO
FOR EACH ROW
BEGIN
SELECT INCREMENTO_CURSO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_CURSO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_GENERO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_GENERO" 
BEFORE INSERT ON TB_GENERO
FOR EACH ROW
BEGIN
SELECT INCREMENTO_GENERO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_GENERO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_MATERIA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_MATERIA" 
BEFORE INSERT ON TB_MATERIA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_MATERIA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_MATERIA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_MATRICULA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_MATRICULA" 
BEFORE INSERT ON TB_MATRICULA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_MATRICULA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_MATRICULA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_ROL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_ROL" 
BEFORE INSERT ON TB_ROL
FOR EACH ROW
BEGIN
SELECT INCREMENTO_ROL.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_ROL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_TAREA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_TAREA" 
BEFORE INSERT ON TB_TAREA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_TAREA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_TAREA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_TAREA_ENTREGADA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_TAREA_ENTREGADA" 
BEFORE INSERT ON TB_TAREA_ENTREGADA
FOR EACH ROW
BEGIN
SELECT INCREMENTO_TAREA_ENTREGADA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_TAREA_ENTREGADA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "C##PIS_U"."TRIG_USUARIO" 
BEFORE INSERT ON TB_USUARIO
FOR EACH ROW
BEGIN
SELECT INCREMENTO_USUARIO.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "C##PIS_U"."TRIG_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_CARRERA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_CARRERA" (
    p_id IN NUMBER DEFAULT NULL,
    p_facultad IN VARCHAR2 DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_id_asignado IN NUMBER DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
    v_carrera TB_CARRERA%ROWTYPE;
    v_carreras SYS_REFCURSOR;
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_CARRERA (ID, CR_FACULTAD, NOMBRE, ESTADO, DESCRIPCION, ID_ASIGNADO)
        VALUES (p_id, p_facultad, p_nombre, p_estado, p_descripcion, p_id_asignado);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_CARRERA
        SET CR_FACULTAD = NVL(p_facultad, CR_FACULTAD),
            NOMBRE = NVL(p_nombre, NOMBRE),
            ESTADO = NVL(p_estado, ESTADO),
            DESCRIPCION = NVL(p_descripcion, DESCRIPCION),
            ID_ASIGNADO = NVL(p_id_asignado, ID_ASIGNADO)
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_CARRERA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        SELECT * INTO v_carrera
        FROM TB_CARRERA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_ALL' THEN
        OPEN v_carreras FOR
        SELECT *
        FROM TB_CARRERA;

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_carrera;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_CURSO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_CURSO" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_id_carrera IN NUMBER DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
    v_curso TB_CURSO%ROWTYPE;
    v_cursos SYS_REFCURSOR;
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_CURSO (ID, NOMBRE, DESCRIPCION, ID_CARRERA, ESTADO)
        VALUES (p_id, p_nombre, p_descripcion, p_id_carrera, p_estado);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_CURSO
        SET NOMBRE = NVL(p_nombre, NOMBRE),
            DESCRIPCION = NVL(p_descripcion, DESCRIPCION),
            ID_CARRERA = NVL(p_id_carrera, ID_CARRERA),
            ESTADO = NVL(p_estado, ESTADO)
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_CURSO
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        SELECT * INTO v_curso
        FROM TB_CURSO
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_ALL' THEN
        OPEN v_cursos FOR
        SELECT *
        FROM TB_CURSO;

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_curso;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_GENERO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_GENERO" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
    v_genero TB_GENERO%ROWTYPE;
    v_generos SYS_REFCURSOR;
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_GENERO (ID, NOMBRE, DESCRIPCION, ESTADO)
        VALUES (p_id, p_nombre, p_descripcion, p_estado);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_GENERO
        SET NOMBRE = NVL(p_nombre, NOMBRE),
            DESCRIPCION = NVL(p_descripcion, DESCRIPCION),
            ESTADO = NVL(p_estado, ESTADO)
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_GENERO
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        SELECT * INTO v_genero
        FROM TB_GENERO
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_ALL' THEN
        OPEN v_generos FOR
        SELECT *
        FROM TB_GENERO;

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_genero;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_MATERIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_MATERIA" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_ma_nota IN NUMBER DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_id_curso IN NUMBER DEFAULT NULL,
    p_id_docente IN NUMBER DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
    v_materia TB_MATERIA%ROWTYPE;
    v_materias SYS_REFCURSOR;
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_MATERIA (ID, NOMBRE, DESCRIPCION, MA_NOTA, ESTADO, ID_CURSO, ID_DOCENTE)
        VALUES (p_id, p_nombre, p_descripcion, p_ma_nota, p_estado, p_id_curso, p_id_docente);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_MATERIA
        SET NOMBRE = NVL(p_nombre, NOMBRE),
            DESCRIPCION = NVL(p_descripcion, DESCRIPCION),
            MA_NOTA = NVL(p_ma_nota, MA_NOTA),
            ESTADO = NVL(p_estado, ESTADO),
            ID_CURSO = NVL(p_id_curso, ID_CURSO),
            ID_DOCENTE = NVL(p_id_docente, ID_DOCENTE)
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_MATERIA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        SELECT * INTO v_materia
        FROM TB_MATERIA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_ALL' THEN
        OPEN v_materias FOR
        SELECT *
        FROM TB_MATERIA;

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_materia;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_MATRICULA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_MATRICULA" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_mt_numero_matricula IN VARCHAR2 DEFAULT NULL,
    p_mt_estado_estudiante IN VARCHAR2 DEFAULT NULL,
    p_mt_nota_final IN NUMBER DEFAULT NULL,
    p_id_estudiante IN NUMBER DEFAULT NULL,
    p_id_curso IN NUMBER DEFAULT NULL,
    p_mt_fecha_inicio IN DATE DEFAULT NULL,
    p_mt_fecha_culminacion IN DATE DEFAULT NULL,
    p_mt_estado_matricula IN VARCHAR2 DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
    v_matricula TB_MATRICULA%ROWTYPE;
    v_matriculas SYS_REFCURSOR;
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_MATRICULA (ID, NOMBRE, DESCRIPCION, ESTADO, MT_NUMERO_MATRICULA, MT_ESTADO_ESTUDIANTE,
                                  MT_NOTA_FINAL, ID_ESTUDIANTE, ID_CURSO, MT_FECHA_INICIO, MT_FECHA_CULMINACION,
                                  MT_ESTADO_MATRICULA)
        VALUES (p_id, p_nombre, p_descripcion, p_estado, p_mt_numero_matricula, p_mt_estado_estudiante,
                p_mt_nota_final, p_id_estudiante, p_id_curso, p_mt_fecha_inicio, p_mt_fecha_culminacion,
                p_mt_estado_matricula);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_MATRICULA
        SET NOMBRE = NVL(p_nombre, NOMBRE),
            DESCRIPCION = NVL(p_descripcion, DESCRIPCION),
            ESTADO = NVL(p_estado, ESTADO),
            MT_NUMERO_MATRICULA = NVL(p_mt_numero_matricula, MT_NUMERO_MATRICULA),
            MT_ESTADO_ESTUDIANTE = NVL(p_mt_estado_estudiante, MT_ESTADO_ESTUDIANTE),
            MT_NOTA_FINAL = NVL(p_mt_nota_final, MT_NOTA_FINAL),
            ID_ESTUDIANTE = NVL(p_id_estudiante, ID_ESTUDIANTE),
            ID_CURSO = NVL(p_id_curso, ID_CURSO),
            MT_FECHA_INICIO = NVL(p_mt_fecha_inicio, MT_FECHA_INICIO),
            MT_FECHA_CULMINACION = NVL(p_mt_fecha_culminacion, MT_FECHA_CULMINACION),
            MT_ESTADO_MATRICULA = NVL(p_mt_estado_matricula, MT_ESTADO_MATRICULA)
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_MATRICULA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        SELECT * INTO v_matricula
        FROM TB_MATRICULA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_ALL' THEN
        OPEN v_matriculas FOR
        SELECT *
        FROM TB_MATRICULA;

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_matricula;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_ROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_ROL" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_ROL (ID, NOMBRE, DESCRIPCION, ESTADO)
        VALUES (p_id, p_nombre, p_descripcion, p_estado);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_ROL
        SET NOMBRE = p_nombre,
            DESCRIPCION = p_descripcion,
            ESTADO = p_estado
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_ROL
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        
        NULL;

    ELSIF p_accion = 'GET_ALL' THEN
       
        NULL; 

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_rol;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_TAREA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_TAREA" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_ta_fecha_creacion IN DATE DEFAULT NULL,
    p_ta_fecha_entrega IN DATE DEFAULT NULL,
    p_descripcion IN NVARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_id_materia IN NUMBER DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_TAREA (ID, NOMBRE, TA_FECHA_CREACION, TA_FECHA_ENTREGA, DESCRIPCION, ESTADO, ID_MATERIA)
        VALUES (p_id, p_nombre, p_ta_fecha_creacion, p_ta_fecha_entrega, p_descripcion, p_estado, p_id_materia);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_TAREA
        SET NOMBRE = p_nombre,
            TA_FECHA_CREACION = p_ta_fecha_creacion,
            TA_FECHA_ENTREGA = p_ta_fecha_entrega,
            DESCRIPCION = p_descripcion,
            ESTADO = p_estado,
            ID_MATERIA = p_id_materia
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_TAREA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
                NULL;

    ELSIF p_accion = 'GET_ALL' THEN
      
        NULL; 

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_tarea;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_TAREA_ENTREGADA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_TAREA_ENTREGADA" (
    p_id IN NUMBER DEFAULT NULL,
    p_descripcion IN NVARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_te_nota IN NUMBER DEFAULT NULL,
    p_id_estudiante IN NUMBER DEFAULT NULL,
    p_id_tarea IN NUMBER DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_TAREA_ENTREGADA (ID, DESCRIPCION, ESTADO, TE_NOTA, ID_ESTUDIANTE, ID_TAREA)
        VALUES (p_id, p_descripcion, p_estado, p_te_nota, p_id_estudiante, p_id_tarea);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_TAREA_ENTREGADA
        SET DESCRIPCION = p_descripcion,
            ESTADO = p_estado,
            TE_NOTA = p_te_nota,
            ID_ESTUDIANTE = p_id_estudiante,
            ID_TAREA = p_id_tarea
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_TAREA_ENTREGADA
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        
        NULL; 

    ELSIF p_accion = 'GET_ALL' THEN
       
        NULL; 

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_tarea_entregada;

/
--------------------------------------------------------
--  DDL for Procedure GESTIONAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PIS_U"."GESTIONAR_USUARIO" (
    p_id IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2 DEFAULT NULL,
    p_apellido IN VARCHAR2 DEFAULT NULL,
    p_estado IN CHAR DEFAULT NULL,
    p_usu_correo_electronico IN VARCHAR2 DEFAULT NULL,
    p_usu_contrasenia IN VARCHAR2 DEFAULT NULL,
    p_id_rol IN NUMBER DEFAULT NULL,
    p_id_genero IN NUMBER DEFAULT NULL,
    p_descripcion IN VARCHAR2 DEFAULT NULL,
    p_cedula IN VARCHAR2 DEFAULT NULL,
    p_telefono IN VARCHAR2 DEFAULT NULL,
    p_accion IN VARCHAR2
)
AS
    v_usuario TB_USUARIO%ROWTYPE;
    v_usuarios SYS_REFCURSOR;
BEGIN
    IF p_accion = 'INSERT' THEN
        INSERT INTO TB_USUARIO (ID, NOMBRE, APELLIDO, ESTADO, USU_CORREO_ELECTRONICO, USU_CONTRASENIA,
                                ID_ROL, ID_GENERO, DESCRIPCION, CEDULA, TELEFONO)
        VALUES (p_id, p_nombre, p_apellido, p_estado, p_usu_correo_electronico, p_usu_contrasenia,
                p_id_rol, p_id_genero, p_descripcion, p_cedula, p_telefono);

    ELSIF p_accion = 'UPDATE' THEN
        UPDATE TB_USUARIO
        SET NOMBRE = NVL(p_nombre, NOMBRE),
            APELLIDO = NVL(p_apellido, APELLIDO),
            ESTADO = NVL(p_estado, ESTADO),
            USU_CORREO_ELECTRONICO = NVL(p_usu_correo_electronico, USU_CORREO_ELECTRONICO),
            USU_CONTRASENIA = NVL(p_usu_contrasenia, USU_CONTRASENIA),
            ID_ROL = NVL(p_id_rol, ID_ROL),
            ID_GENERO = NVL(p_id_genero, ID_GENERO),
            DESCRIPCION = NVL(p_descripcion, DESCRIPCION),
            CEDULA = NVL(p_cedula, CEDULA),
            TELEFONO = NVL(p_telefono, TELEFONO)
        WHERE ID = p_id;

    ELSIF p_accion = 'DELETE' THEN
        DELETE FROM TB_USUARIO
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_BY_ID' THEN
        SELECT * INTO v_usuario
        FROM TB_USUARIO
        WHERE ID = p_id;

    ELSIF p_accion = 'GET_ALL' THEN
        OPEN v_usuarios FOR
        SELECT *
        FROM TB_USUARIO;

    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Acción no válida. Las opciones válidas son INSERT, UPDATE, DELETE, GET_BY_ID o GET_ALL.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END gestionar_usuario;

/
--------------------------------------------------------
--  Constraints for Table TB_CARRERA
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_CARRERA" MODIFY ("CR_FACULTAD" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CARRERA" MODIFY ("ID_ASIGNADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CARRERA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CARRERA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CARRERA" ADD CONSTRAINT "TB_CARRERA_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_CARRERA_PK"  ENABLE;
  ALTER TABLE "C##PIS_U"."TB_CARRERA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CURSO
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_CURSO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CURSO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CURSO" MODIFY ("ID_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_CURSO" MODIFY ("ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_GENERO
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_GENERO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_GENERO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_GENERO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_GENERO" ADD CONSTRAINT "TB_GENERO_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_GENERO_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_MATERIA
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_MATERIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATERIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATERIA" MODIFY ("MA_NOTA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATERIA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATERIA" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATERIA" MODIFY ("ID_DOCENTE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATERIA" ADD CONSTRAINT "TB_MATERIA_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_MATERIA_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_MATRICULA
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("MT_NUMERO_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("MT_ESTADO_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("MT_NOTA_FINAL" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("MT_FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("MT_FECHA_CULMINACION" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" MODIFY ("MT_ESTADO_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_MATRICULA" ADD CONSTRAINT "TB_MATRICULA_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_MATRICULA_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ROL
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_ROL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_ROL" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_ROL" ADD CONSTRAINT "TB_ROL_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_ROL_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_TAREA
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_TAREA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA" MODIFY ("TA_FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA" MODIFY ("TA_FECHA_ENTREGA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA" MODIFY ("ID_MATERIA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA" ADD CONSTRAINT "TB_TAREA_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_TAREA_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_TAREA_ENTREGADA
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" MODIFY ("TE_NOTA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_TAREA_ENTREGADA" ADD CONSTRAINT "TB_TAREA_ENTREGADA_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_TAREA_ENTREGADA_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_USUARIO
--------------------------------------------------------

  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("USU_CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("USU_CONTRASENIA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("ID_GENERO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "C##PIS_U"."TB_USUARIO" ADD CONSTRAINT "TB_USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX "C##PIS_U"."TB_USUARIO_PK"  ENABLE;
  ALTER TABLE "C##PIS_U"."TB_USUARIO" MODIFY ("ID_ROL" NOT NULL ENABLE);
